version: '3.8'
services:
  hugo-site:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/usr/share/nginx/site
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6969:80"
