name: Deploy Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v4.1.4

      # build and push container image
      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_TAG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # deploy to a container registry (e.g., Docker Hub)
      - name: Deploy Container
        uses: docker/deploy-container@v1
        with:
          repository: ${{ secrets.CONTAINER_REPO }}
          tag: ${{ secrets.CONTAINER_TAG }}