name: HTML Proofer

on: [pull_request]

jobs:
  proof-html:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v4.1.4
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
    # install Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    # build website
    - name: Build
      run: hugo --minify
    
    # Run HTML Proofer
    - uses: anishathalye/proof-html@v2
      with:
        directory: ./public
