name: Lighthouse
on: [pull_request]

jobs:
  score-check:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.1.4
    - run: npm install
    # Run Lighthouse check
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        urls: 'https://www.foo.software,https://www.foo.software/contact'

    # Verify Lighthouse scores
    - name: Handle Lighthouse Check results
      uses: ./
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "95"
        minBestPracticesScore: "85"
        minPerformanceScore: "60"
        minProgressiveWebAppScore: "50"
        minSeoScore: "90"
